import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import { Navigation } from "@/components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} >
      <ClerkProvider>
        <body className="antialiased">
          <Navigation />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
